name: docker compose
description: 'up docker compose ci env'

branding:
  icon: 'archive'
  color: 'blue'

inputs:
  docker-compose-file:
    required: false
    description: docker-compose.yml path
    default: docker-compose.ci.yml

runs:
  using: 'composite'
  steps:
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles(format('{0}', inputs.docker-compose-file)) }}

    - name: Build the stack
      shell: sh
      run: docker compose -f ${{ inputs.docker-compose-file }} up -d
